- hosts: localhost
  connection: local
  become: yes
  gather_facts: no

  tasks:
  - name: Create group
    group: 
      name: "{{ item.group }}"
      state: present
      gid: "{{ item.gid }}"
    loop:
      - { group: vault, gid: 501 }

  - name: Create user
    user:
      name: "{{item.user}}"
      state: present
      shell: /bin/bash
      createhome: yes
      uid: "{{item.uid}}"
      group: "{{item.group}}"
    loop:
      - { user: vault, uid: 501, group: vault }

